version: "3.8"
services:
  cs-generator:
    build: ../Containers/CodeStreamGenerator
    image: csgenerator:latest
    command: "TEST"
    volumes:
      - qc-volume:/QualitasCorpus
      - ../Containers/CodeStreamGenerator/test:/app/test  # Mount the local test directory to /app/test
    environment:
      DELAY: 5  # Shorten the delay for testing
      TARGET: "cs-consumer:3000"

  cs-consumer:
    build: ./Containers/CodeStreamConsumer
    image: csconsumer:latest
    volumes:
      - ./Containers/CodeStreamConsumer/src:/app/src
    ports:
      - 8080:3000
    entrypoint: ["node", "/app/src/index.js"]

volumes:
  qc-volume:
    external: true

