version: "3.8"
services:
  cs-generator:
    image: csgenerator
    command: "./generate-code-stream.sh"
    volumes:
      # Mount the correct directory for Java files
      - ./files.txt:/root/files.txt
      - ./Containers/CodeStreamGenerator/test:/test
    environment:
      DELAY: 5000
      TARGET: "cs-consumer:3000"

  cs-consumer:
    image: csconsumer
    volumes:
      - ./Containers/CodeStreamConsumer/src:/app/src
    ports:
      - "8080:3000"

volumes:
  qc-volume: {}
