version: "3.8"

services:
  cs-generator:
    build: ./Containers/CodeStreamGenerator
    image: csgenerator:latest
    command: "TEST"
    environment:
      DELAY: 5                  # Delay between sending files
      TARGET: "cs-consumer:3000"
    volumes:
      - qc-volume:/QualitasCorpus  # Only mount corpus, not test files
      - ./Containers/CodeStreamGenerator/test:/app/test

  cs-consumer:
    build: ./Containers/CodeStreamConsumer
    image: csconsumer:latest
    ports:
      - 8080:3000
    volumes:
      - ./Containers/CodeStreamConsumer/src:/app/src  # Mount consumer code
    entrypoint: ["node", "/app/src/index.js"]

volumes:
  qc-volume:
    external: true
