version: "3.8"

services:
  cs-generator:
    image: csgenerator
    command: "TEST"
    volumes:
    - ./BigDataAnalytics-main/BigDataAnalytics/Containers/CodeStreamGenerator/test:/app/Containers/CodeStreamGenerator/test 
  environment:
    environment:
      - TARGET=cs-consumer:3000
      - DELAY=0

  cs-consumer:
    image: csconsumer
    volumes:
      - ./Containers/CodeStreamConsumer/src:/app/src
    ports:
      - 8080:3000

volumes:
  qc-volume:
    external: true

