version: "3.8"

services:
  cs-generator:
    image: csgenerator
    command: "/app/generate-code-stream.sh"
    volumes:
      - qc-volume:/qc                        # Share the qc-volume for data between containers
      - ./Containers/CodeStreamGenerator/test:/qc   # Mount the directory with your .java files to /qc
      - /Containers/CodeStreamGenerator/generate-code-stream.sh:/app/generate-code-stream.sh
    environment:
      - TARGET=cs-consumer:3000
      - DELAY=0

  cs-consumer:
    image: csconsumer
    volumes:
      - ./Containers/CodeStreamConsumer/src:/app/src
      - qc-volume:/qc        # <--- Shared volume, so the consumer can access the processed files
    ports:
      - 8080:3000

volumes:
  qc-volume:
    external: true

