# Docker Compose for Stream-of-code test
# Connects:
# - CodeStreamGenerator
# - CodeStreamConsumer
# - QualitasCorpus Volume

version: "3.8"
services:
  cs-generator:
    image: csgenerator
    command: "./generate-code-stream.sh"
    volumes:
      - /home/vboxuser/BigDataAnalytics-main/BigDataAnalytics/Containers/CorpusGetter/QualitasCorpus:/QualitasCorpus  # Absolute path to QualitasCorpus
    environment:
      DELAY: 3
      TARGET: "cs-consumer:3000"

  cs-consumer:
    image: csconsumer
    volumes:
      - ./Containers/CodeStreamConsumer/src:/app/src
    ports:
      - "8080:3000"

volumes:
  qc-volume: {}



   

    
