version: "3.8"

services:
  cs-generator:
    image: csgenerator
    command: "TEST"
    volumes:
      - qc-volume:/qc        # <--- MOUNT qc VOLUME HERE
    environment:
      - TARGET=cs-consumer:3000
      - DELAY=0

  cs-consumer:
    image: csconsumer
    volumes:
      - ./Containers/CodeStreamConsumer/src:/app/src
      - qc-volume:/qc        # <--- MOUNT qc VOLUME HERE
    ports:
      - 8080:3000

volumes:
  qc-volume:
    external: true
